# Generated by Django 3.2.4 on 2024-01-10 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('idMateria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('semestre', models.CharField(max_length=45)),
                ('creditos', models.IntegerField()),
            ],
            options={
                'db_table': 'Materia',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('idPeriodo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Periodo',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_Rol', models.AutoField(primary_key=True, serialize=False)),
                ('Descripción', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('idSeguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('parcial', models.CharField(max_length=45)),
                ('Periodo_idPeriodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.periodo')),
            ],
            options={
                'db_table': 'Seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Jefa',
            fields=[
                ('id_Jefa', models.AutoField(primary_key=True, serialize=False)),
                ('Rol_id_Rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Jefa',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('idDocente', models.AutoField(primary_key=True, serialize=False)),
                ('Rol_id_Rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Docente',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.AutoField(primary_key=True, serialize=False)),
                ('Rol_id_Rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Alumno',
            },
        ),
    ]
