# Generated by Django 3.2.4 on 2023-09-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idUsu', models.CharField(db_column='idCliente', max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='nombre', max_length=50)),
                ('pas', models.CharField(db_column='password', max_length=50)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
