# Generated by Django 3.2.4 on 2023-11-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alumno_docente_jefa_materia_rol_seguimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encuestadesatisfaccion',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
